domain_id: 1  # Domain id
interface: "lo" # Interface

set_zero: false # Zero the motors on startup

# Order: L_hip L_thigh L_calf L_wheel R_hip R_thigh R_calf R_wheel
motor_offset: [1.0472, -1.7453, 3.229, 0, -1.0472, -1.7453, 3.229, 0]
direction: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
pos_limit:
  - [-1.0472, 0.6108]
  - [0, 1.7453]
  - [-3.229, 0]
  - [-.inf, .inf]
  - [-0.6108, 1.0472]
  - [0, 1.7453]
  - [-3.229, 0]
  - [-.inf, .inf]
